version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shazam_telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - downloads:/app/downloads
      - users:/app/users.json
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped

volumes:
  downloads:
  users: