version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shazam_telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./data:/app/data  # Single directory for all persistent data
    restart: unless-stopped